[package]
name = "dyn-histogram"
version = "0.1.0"
authors = ["Stefan Kaufhold <cere@fastmail.fm>"]
edition = "2018"

[dependencies]
binary-heap-plus = "0.1.4"
num = "0.2.0"
ord_subset = "3"
id-vec = "0.5"